name: Build

on:
  push:
    branches: [ main ]
    tags:
      - "*.*.*"    
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run lint
      run: make lint || true

    - name: Build unsigned IPA
      run: make ipa-unsigned

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: devicekit-ios-unsigned-ipa
        path: build/export/*-unsigned.ipa
        retention-days: 4

    - name: Upload to GitHub Release
      if: github.ref_type == 'tag' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
      with:
        name: Version ${{ github.ref_name }}
        files: build/export/*-unsigned.ipa

